Update deploy_ec2.yml

diff --git a/.github/workflows/deploy_ec2.yml b/.github/workflows/deploy_ec2.yml
--- a/.github/workflows/deploy_ec2.yml
+++ b/.github/workflows/deploy_ec2.yml
@@ -36,7 +36,27 @@ jobs:
           
     - name: Pull Latest Code from webtoon-crawler
       run: |
-        aws ssm send-command \
+        # Send the command
+        command_id=$(aws ssm send-command \
           --document-name "AWS-RunShellScript" \
-          --instance-ids  $EC2_INSTANCE_ID \
-          --parameters commands="cd $EC2_REPOSITORY/crawler && sudo -u $EC2_USER git pull origin master"
+          --instance-ids $EC2_INSTANCE_ID \
+          --parameters commands="cd $EC2_REPOSITORY/crawler && sudo -u $EC2_USER git pull origin master" \
+          --query "Command.CommandId" \
+          --output text)
+
+        # Wait for the command to complete
+        echo "Command sent. Waiting for completion..."
+
+        # Check the status of the command
+        status=$(aws ssm list-command-invocations \
+          --command-id $command_id \
+          --query "CommandInvocations[0].Status" \
+          --output text)
+
+        echo "Command status: $status"
+
+        # Handle failure
+        if [[ "$status" != "Success" ]]; then
+          echo "Command failed with status: $status"
+          exit 1  # Fail the workflow if the command fails
+        fi
